### ISSUE TITLE
Does not work on Django 1.11

### ISSUE THREAD

**Issue by alanjds** [mlavin/django-qjoin#7]
```python
>>> from qjoin.models import QJoin, JoinExpression
ImportError: cannot import name 'ExpressionNode'
```

Looks like Django 1.11 changed ExpressionNode location (if still exists)
``from django.db.models.expressions import ExpressionNode``

**Comment by mlavin** [comment]
The underlying join code isn't part of the public ORM API and changes with nearly every Django release. This started more as a proof of concept and I'm not sure it can ever be much more than that sadly.

**Comment by alanjds** [comment]
I looked at the docs, and for now I think it would be more stable to implement it as a [custom lookup](https://docs.djangoproject.com/en/1.11/ref/models/lookups/).

Would be able to implement such API:
```python
Email.objects.filter(email__join=Bounce.email)
# or outer
Email.objects.filter(email__outerjoin=Bounce.email)
```

Assuming that the [Lookup.process_rhs](https://docs.djangoproject.com/en/1.11/ref/models/lookups/#django.db.models.Lookup.process_lhs) can inject the tables via ``.extra()``

This looks remotely feasible for you?

**Comment by mlavin** [comment]
Yes the lookup API is more promising than expressions because you have access to both the left and right hand sides without the weird wrapper expression.
